# Generated by Django 3.2.5 on 2023-11-14 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TimeSeriesDatasets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataset_id', models.IntegerField()),
                ('file', models.FileField(upload_to='')),
                ('input_values', models.IntegerField()),
            ],
        ),
    ]
