# Generated by Django 3.2.5 on 2023-11-14 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeseries_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeseriesdatasets',
            name='input_values',
            field=models.IntegerField(editable=False, null=True),
        ),
    ]
