# Generated by Django 4.2.5 on 2023-11-28 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeseries_api', '0003_selectedfeature_timeseriesdatasets_model'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SelectedFeature',
        ),
        migrations.AddField(
            model_name='timeseriesdatasets',
            name='selected_features',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
